import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { fetchClient } from "@/lib/FetchClient";
import { generateMetadata } from "@/lib/Seo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const blogData = await fetchClient.fetch(
    "Pages/get/slug/top-wedding-photography-trends-for-2025"
  );
  console.log("blogData", blogData);
  return (
    <html lang="en">
      <div>{JSON.stringify(generateMetadata())}</div>
      {/* {blogData?.data?.metatitle ? (
        <head>
          <title>{blogData?.data?.metatitle || "EventoQ2"}</title>
          <meta name="description" content={blogData?.data?.description} />
        </head>
      ) : (
        <div>{JSON.stringify(generateMetadata())}</div>
      )} */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
